# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'riickk18-reddit-memes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for riickk18-reddit-memes
  pod 'SwiftLint'

  target 'riickk18-reddit-memesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'riickk18-reddit-memesUITests' do
    # Pods for testing
  end

end
